### ISSUE TITLE
More than one exclude issue.

### ISSUE THREAD

**Issue by RinoReyns** [threeal/gcovr-action#100]
It there an option to exclude more than one pattern? In the native "gcovr" you can set  "exclude" parameter multiple times. It this possible here?

**Comment by threeal** [comment]
It is not possible right now, but we can add support to allow that. We just need to allow `exclude` input to parse multiline string, and then set the `--exclude` arguments accordingly.

**Comment by RinoReyns** [comment]
It would be great, because from my point of view other elements works perfect and this is the only missing element. I'm looking forward :)

**Comment by threeal** [comment]
@RinoReyns It's up now, you should be able to use more than one exclude using `@main` branch (since this feature has not been released yet, still waiting some stuffs in #31).

Should be notice, the input is renamed from `exclude` to `excludes`, with `s` suffix.

Sorry for taking a long time to resolve this issue, just let me know if there's anything i could help.

**Comment by RinoReyns** [comment]
@threeal Thank you very much. I have tested it and new feature works perfect. :) I if will have more ideas I will definitely let you know :)
