### ISSUE TITLE
Pip install fails on Arch Linux image

### ISSUE THREAD

**Issue by romangg** [threeal/gcovr-action#217]
[This pipeline](https://github.com/romangg/como/actions/runs/8121755553/job/22200840237) fails due to the action trying to install gcovr into the system directory.

What needs to be done first is to create a virtual environment for Pip. I tried to this before calling into the action with `python -m venv venv && source venv/bin/activate` but it's not reusing the environment inside the action, so it must be done inside the action..

**Comment by threeal** [comment]
Can you try using the main branch instead: `threeal/gcovr-action@xml-out`?

It includes a change that installs gcovr using pipx instead of pip (see #204). By default, pipx should install gcovr to the home directory. However, your runner may need to support pipx in this case.

**Comment by romangg** [comment]
> Can you try using the main branch instead: threeal/gcovr-action@xml-out?

I was using already the xml-out tag. It doesn't include the change to pipx though. I'm now testing with  `threeal/gcovr-action@main`

**Comment by romangg** [comment]
With main tag, I get a different error, now it doesn't find the pipx binary:

```
Error: Failed to restore gcovr cache:
Failed to get PIPX_BIN_DIR: Unable to locate executable file: pipx. 
Please verify either the file path exists or the file can be found within a 
directory specified by the PATH environment variable. Also check the file mode 
to verify the file is executable.
```
[source](https://github.com/romangg/como/actions/runs/8123684702/job/22204699569)

**Comment by threeal** [comment]
I'm sorry, I meant the `main` tag. However, as mentioned earlier, this change requires [pipx](https://github.com/pypa/pipx) to install gcovr.

Since your runner doesn't support pipx, I suggest updating the image to support pipx, as GitHub's default images also support pipx (see [this](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md)). But if you can't do this, adding a step to install pipx in the workflow may be helpful.

Another hack may be to install gcovr directly before running this action. You can use Arch Linux's package manager to do this, or use pip to install it in the home directory.

**Comment by romangg** [comment]
Ok, installing pipx seems to be a solution. Not sure if one should expect that or the action could try to install it first via pip or something but that it's in official GitHub images is an argument for the former. Thanks!
